global:
  revisionHistoryLimit: 3  

controller:
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  

configs:
  cm:
    timeout.reconciliation: 45s  
    admin.enabled: true
    exec.enabled: "true"
    url: "https://argocd.meditrack-app.me"
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: "${sso_client_id}"
            clientSecret: "${sso_client_secret}"
            orgs:
            - name: devops-homelab
              teams:
              - devops-team
  rbac:
    policy.csv: |
      g, devops-homelab:devops-team, role:org-admin

  credentialTemplates:
    https-creds:
      url: https://github.com/devops-homelab
      password: "${pat_token}"
      username: "${git_username}"

redis-ha:   
  enabled: false  

server:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 75
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  
  ingress:
    enabled: true
    tls: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
    hostname: argocd.meditrack-app.me
    
repoServer:
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true  

applicationSet:
  metrics:
    enabled: true  
  serviceMonitor:
    enabled: true 