installCRDs: true

dashboard:
  enabled: true
  ingress:
    enabled: true
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
    ingressClassName: nginx
    hosts:
      - argo-rollouts.devopshomelab.live
    paths:
      - /
    tls:
      - secretName: argo-rollouts-tls
        hosts:
          - argo-rollouts.devopshomelab.live