kong:
  # DB-less mode
  env:
    database: "off"
  ingressController:
    enabled: true
    ingressClass: kong
    # Enable Gateway API support
    gatewayAPI:
      enabled: true
    env:
      # Enable Gateway API feature gates
      feature_gates: "GatewayAlpha=true"
  admin:
    tls:
      parameters: []