name: Terraform Linting
on:
    pull_request:
        branches:
          - main

jobs:
  tf-lint:
    uses: devops-homelab/homelab-github-reusable-workflows/.github/workflows/tf-lint.yaml
    secrets:
      GITHUB_PAT: ${{ secrets.GH_PAT }}